# Generated by Django 5.1.6 on 2025-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_comment_comment_comment_created_ad_director_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
